image: rocker/tidyverse

stages:
    - test

# dependencies will be stored there and do not have to be reinstalled every time
# for the same branch.
# NOTE: this does not work if the runner changes...
cache:
  # Ommit key to use the same cache across all pipelines and branches
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - /usr/local/lib/R/site-library

build:
    stage: test
    tags:
        - envinf1
    script:
         # checks if the packages from the Imports field are already installed in the cache
        - R -e 'source("R/ci-setup.R")'
        - R -e 'print(.libPaths())'
        #- R -e 'print(rownames(installed.packages()))'
        - R CMD build . --no-build-vignettes --no-manual
        - R CMD check $(ls -1t *.tar.gz | head -n 1) --no-build-vignettes --no-manual
    artifacts:
        paths:
          - builds/

